name: Build GaanaPy Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Image
        run: |
         docker build . -t zingytomato/gaanapy:latest 
      - name: Push to Docker Hub
        run: |
          docker push zingytomato/gaanapy:latest 
          docker logout
